/**
 * Contains PostgreSQL schema objects.
 */
package cz.startnet.utils.pgdiff.schema

import cz.startnet.utils.pgdiff.schema.PgDatabase
import java.io.BufferedReader
import java.io.UnsupportedEncodingException
import java.lang.UnsupportedOperationException
import cz.startnet.utils.pgdiff.loader.PgDumpLoader
import cz.startnet.utils.pgdiff.parsers.CreateSchemaParser
import cz.startnet.utils.pgdiff.parsers.CreateExtensionParser
import cz.startnet.utils.pgdiff.parsers.CreateTableParser
import cz.startnet.utils.pgdiff.parsers.AlterRelationParser
import cz.startnet.utils.pgdiff.parsers.CreateSequenceParser
import cz.startnet.utils.pgdiff.parsers.AlterSequenceParser
import cz.startnet.utils.pgdiff.parsers.CreateIndexParser
import cz.startnet.utils.pgdiff.parsers.CreateViewParser
import cz.startnet.utils.pgdiff.parsers.CreateTriggerParser
import cz.startnet.utils.pgdiff.parsers.CreateFunctionParser
import cz.startnet.utils.pgdiff.parsers.CreateTypeParser
import cz.startnet.utils.pgdiff.parsers.CommentParser
import cz.startnet.utils.pgdiff.parsers.GrantRevokeParser
import cz.startnet.utils.pgdiff.parsers.CreatePolicyParser
import cz.startnet.utils.pgdiff.parsers.CreateRuleParser
import java.io.FileInputStream
import java.io.FileNotFoundException
import cz.startnet.utils.pgdiff.loader.FileException
import java.text.MessageFormat
import java.io.IOException
import java.lang.StringBuilder
import java.lang.RuntimeException
import cz.startnet.utils.pgdiff.schema.PgRelation
import cz.startnet.utils.pgdiff.PgDiffUtils
import cz.startnet.utils.pgdiff.schema.PgRule
import cz.startnet.utils.pgdiff.schema.PgColumn
import java.util.Collections
import cz.startnet.utils.pgdiff.schema.PgIndex
import cz.startnet.utils.pgdiff.schema.PgSchema
import cz.startnet.utils.pgdiff.schema.PgInheritedColumn
import cz.startnet.utils.pgdiff.schema.PgConstraint
import cz.startnet.utils.pgdiff.schema.PgPolicy
import cz.startnet.utils.pgdiff.schema.PgTable
import cz.startnet.utils.pgdiff.schema.PgColumnPrivilege
import cz.startnet.utils.pgdiff.schema.PgColumnUtils
import cz.startnet.utils.pgdiff.schema.PgFunction
import cz.startnet.utils.pgdiff.schema.PgSequence
import cz.startnet.utils.pgdiff.schema.PgType
import cz.startnet.utils.pgdiff.schema.PgView
import cz.startnet.utils.pgdiff.schema.PgTrigger.EventTimeQualification
import java.util.HashMap
import cz.startnet.utils.pgdiff.schema.PgTrigger
import cz.startnet.utils.pgdiff.schema.PgExtension
import java.util.Locale
import cz.startnet.utils.pgdiff.schema.PgRelationPrivilege
import cz.startnet.utils.pgdiff.schema.PgSequencePrivilege
import java.lang.NumberFormatException
import cz.startnet.utils.pgdiff.parsers.ParserUtils
import kotlin.Throws
import kotlin.jvm.JvmStatic
import java.io.PrintWriter
import cz.startnet.utils.pgdiff.PgDiffArguments
import java.io.OutputStreamWriter
import cz.startnet.utils.pgdiff.PgDiff
import cz.startnet.utils.pgdiff.SearchPathHelper
import cz.startnet.utils.pgdiff.PgDiffTriggers
import cz.startnet.utils.pgdiff.PgDiffRules
import cz.startnet.utils.pgdiff.PgDiffFunctions
import cz.startnet.utils.pgdiff.PgDiffViews
import cz.startnet.utils.pgdiff.PgDiffConstraints
import cz.startnet.utils.pgdiff.PgDiffIndexes
import cz.startnet.utils.pgdiff.PgDiffTables
import cz.startnet.utils.pgdiff.PgDiffSequences
import cz.startnet.utils.pgdiff.PgDiffPolicies
import cz.startnet.utils.pgdiff.PgDiffTypes
import cz.startnet.utils.pgdiff.PgDiffGrant
import java.util.ResourceBundle
import java.util.SortedMap
import java.nio.charset.Charset
