
CREATE TABLE companies (
	id bigint NOT NULL
);

ALTER TABLE companies OWNER TO postgres;

ALTER TABLE companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE companies
	ADD CONSTRAINT companies_pkey PRIMARY KEY (id);
