name: Gradle

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fatJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build distribution
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: fatJar distTar distZip
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
      - uses: actions/upload-artifact@v2
        with:
          name: fat-jar
          path: |
            build/libs/*-fat.jar
      - uses: actions/upload-artifact@v2
        with:
          name: distributions
          path: |
            build/distributions/*.*
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            build/libs/*-fat.jar
            build/distributions/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
