# This is a basic workflow to help you get started with Actions

name: Gradle

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fatJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: fatJar
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
      - name: Archive fatJar
        uses: actions/upload-artifact@v2
        with:
          name: fat-jar
          path: build/libs
